"""add_short_link_default_action

Revision ID: 32736aed11b0
Revises: 20240816_multi_tenant
Create Date: 2026-08-15 05:22:36.011651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32736aed11b0'
down_revision = '20240816_multi_tenant'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_access_logs_dedup', table_name='access_logs')
    op.drop_index('idx_access_logs_domain', table_name='access_logs')
    op.drop_index('idx_access_logs_plus8', table_name='access_logs')
    op.drop_index('idx_access_logs_short_link', table_name='access_logs')
    op.drop_index('idx_short_links_domain', table_name='short_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_short_links_domain', 'short_links', ['domain_id'], unique=False)
    op.create_index('idx_access_logs_short_link', 'access_logs', ['short_link_id'], unique=False)
    op.create_index('idx_access_logs_plus8', 'access_logs', ['short_link_id', 'accessed_at_plus8'], unique=False)
    op.create_index('idx_access_logs_domain', 'access_logs', ['domain_id'], unique=False)
    op.create_index('idx_access_logs_dedup', 'access_logs', ['short_link_id', 'ip', 'dedup_bucket'], unique=False)
    # ### end Alembic commands ###
