"""add_access_rule_proxy_and_bot_flags

Revision ID: b1e5f6851085
Revises: db8f98f91f7c
Create Date: 2026-08-15 05:47:12.558659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e5f6851085'
down_revision = 'db8f98f91f7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_rules', sa.Column('allow_proxy', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('access_rules', sa.Column('allow_bot', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_rules', 'allow_bot')
    op.drop_column('access_rules', 'allow_proxy')
    # ### end Alembic commands ###
