"""add_short_link_default_action

Revision ID: db8f98f91f7c
Revises: 32736aed11b0
Create Date: 2026-08-15 05:23:16.770032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8f98f91f7c'
down_revision = '32736aed11b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'short_links',
        sa.Column('default_action', sa.String(length=16), server_default='allow', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_links', 'default_action')
    # ### end Alembic commands ###
