"""Stable error codes returned by the public API."""

from enum import StrEnum


class ErrorCode(StrEnum):
    CONFLICT = "CONFLICT"
    DOMAIN_CONFLICT = "DOMAIN_CONFLICT"
    DOMAIN_IN_USE = "DOMAIN_IN_USE"
    IP_BLACKLIST_CONFLICT = "IP_BLACKLIST_CONFLICT"
    INVALID_CURSOR = "INVALID_CURSOR"
    LAST_ADMIN_REQUIRED = "LAST_ADMIN_REQUIRED"
    NOT_FOUND = "NOT_FOUND"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    SHORT_CODE_CONFLICT = "SHORT_CODE_CONFLICT"
    UNAUTHORIZED = "UNAUTHORIZED"
    USERNAME_CONFLICT = "USERNAME_CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
